apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wezvatech-capstoneproject
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rahima-farzana/ledger-deployment.git
        revision: HEAD
        directories:
          - path: envs/*
  template:
    metadata:
      name: '{{path.basename}}-ledger'
    spec:
      project: default
      source:
        repoURL: https://github.com/rahima-farzana/ledger-deployment.git
        targetRevision: main
        path: mychart
        helm:
          valueFiles:
            - '../envs/{{path.basename}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

